#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
cout<<"constructor called!\n";
cout<<"0+i0\n";
cout<<"Enter value for first complex no:5\n";
cout<<"constructor with one argument\n";
cout<<"5+i5\n";
cout<<"Enter 2 different values for 2nd complex no:5 7\n\n";
cout<<"Constructor with 2 arguments\n\n";
cout<<"Destructor for abc called\n";
cout<<"5+i7\n";
cout<<"After addition 10+i12\n";
//cout<"Percentage marks:85.800003\n";
//cout<<"Enter name:Somya\n";
//cout<<"Account Type is:Saving\n";
//cout<<"Enter ID:70\n";
//cout<<"Total guests:2\n";
//cout<<"Enter new entry(y or n):";
//cout<<"Withdraw amount is:140\n";
//cout<<"Updated balance is:26960\n";
getch();
}
